import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { AuthGuardService } from './services/auth-guard.service';

const routes: Routes = [
  { path: '', redirectTo: 'agro-tabs', pathMatch: 'full' },
  { path: 'login', loadChildren: './login/login.module#LoginPageModule'},
  { path: 'contact', loadChildren: './contact/contact.module#ContactPageModule', canActivate: [AuthGuardService] },
  { path: 'contact-list', loadChildren: './contact-list/contact-list.module#ContactListPageModule', canActivate: [AuthGuardService] },
  { path: 'product', loadChildren: './product/product.module#ProductPageModule', canActivate: [AuthGuardService] },
  { path: 'product-category', loadChildren: './product-category/product-category.module#ProductCategoryPageModule', canActivate: [AuthGuardService] },
  { path: 'product-category-list', loadChildren: './product-category-list/product-category-list.module#ProductCategoryListPageModule', canActivate: [AuthGuardService] },
  { path: 'product-list', loadChildren: './product-list/product-list.module#ProductListPageModule', canActivate: [AuthGuardService] },
  { path: 'stock-move', loadChildren: './stock-move/stock-move.module#StockMovePageModule', canActivate: [AuthGuardService] },
  { path: 'stock-move-list', loadChildren: './stock-move-list/stock-move-list.module#StockMoveListPageModule', canActivate: [AuthGuardService] },
  { path: 'warehouse', loadChildren: './warehouse/warehouse.module#WarehousePageModule', canActivate: [AuthGuardService] },
  { path: 'warehouse-list', loadChildren: './warehouse-list/warehouse-list.module#WarehouseListPageModule', canActivate: [AuthGuardService] },
  { path: 'cash-move', loadChildren: './cash-move/cash-move.module#CashMovePageModule', canActivate: [AuthGuardService] },
  { path: 'account', loadChildren: './account/account.module#AccountPageModule', canActivate: [AuthGuardService] },
  { path: 'account-list', loadChildren: './account-list/account-list.module#AccountListPageModule', canActivate: [AuthGuardService] },
  { path: 'account-category', loadChildren: './account-category/account-category.module#AccountCategoryPageModule', canActivate: [AuthGuardService] },
  { path: 'account-category-list', loadChildren: './account-category-list/account-category-list.module#AccountCategoryListPageModule', canActivate: [AuthGuardService] },
  { path: 'title', loadChildren: './title/title.module#TitlePageModule', canActivate: [AuthGuardService] },
  { path: 'title-list', loadChildren: './title-list/title-list.module#TitleListPageModule', canActivate: [AuthGuardService] },
  { path: 'cash-move-list', loadChildren: './cash-move-list/cash-move-list.module#CashMoveListPageModule', canActivate: [AuthGuardService] },
  { path: 'currency', loadChildren: './currency/currency.module#CurrencyPageModule', canActivate: [AuthGuardService] },
  { path: 'currency-list', loadChildren: './currency-list/currency-list.module#CurrencyListPageModule', canActivate: [AuthGuardService] },
  { path: 'check', loadChildren: './check/check.module#CheckPageModule', canActivate: [AuthGuardService] },
  { path: 'check-list', loadChildren: './check-list/check-list.module#CheckListPageModule', canActivate: [AuthGuardService] },
  { path: 'receipt', loadChildren: './receipt/receipt.module#ReceiptPageModule', canActivate: [AuthGuardService] },
  { path: 'receipt-list', loadChildren: './receipt-list/receipt-list.module#ReceiptListPageModule', canActivate: [AuthGuardService] },
  { path: 'cash', loadChildren: './cash/cash.module#CashPageModule', canActivate: [AuthGuardService] },
  { path: 'cash-list', loadChildren: './cash-list/cash-list.module#CashListPageModule', canActivate: [AuthGuardService] },
  { path: 'invoice', loadChildren: './invoice/invoice.module#InvoicePageModule', canActivate: [AuthGuardService] },
  { path: 'invoice-list', loadChildren: './invoice-list/invoice-list.module#InvoiceListPageModule', canActivate: [AuthGuardService] },
  { path: 'sale', loadChildren: './sale/sale.module#SalePageModule', canActivate: [AuthGuardService] },
  { path: 'sale-list', loadChildren: './sale-list/sale-list.module#SaleListPageModule', canActivate: [AuthGuardService] },
  { path: 'payment-condition', loadChildren: './payment-condition/payment-condition.module#PaymentConditionPageModule', canActivate: [AuthGuardService] },
  { path: 'payment-condition-list', loadChildren: './payment-condition-list/payment-condition-list.module#PaymentConditionListPageModule', canActivate: [AuthGuardService] },
  { path: 'advance', loadChildren: './advance/advance.module#AdvancePageModule', canActivate: [AuthGuardService] },
  { path: 'config', loadChildren: './config/config.module#ConfigPageModule', canActivate: [AuthGuardService] },
  { path: 'invoice-config', loadChildren: './invoice-config/invoice-config.module#InvoiceConfigPageModule', canActivate: [AuthGuardService] },
  { path: 'user', loadChildren: './user/user.module#UserPageModule', canActivate: [AuthGuardService] },
  { path: 'help', loadChildren: './help/help.module#HelpPageModule', canActivate: [AuthGuardService] },
  { path: 'help-list', loadChildren: './help-list/help-list.module#HelpListPageModule', canActivate: [AuthGuardService] },
  { path: 'planned-list', loadChildren: './planned-list/planned-list.module#PlannedListPageModule', canActivate: [AuthGuardService] },
  { path: 'purchase', loadChildren: './purchase/purchase.module#PurchasePageModule', canActivate: [AuthGuardService] },
  { path: 'salary', loadChildren: './salary/salary.module#SalaryPageModule', canActivate: [AuthGuardService] },
  { path: 'service', loadChildren: './service/service.module#ServicePageModule', canActivate: [AuthGuardService] },
  { path: 'purchase-list', loadChildren: './purchase-list/purchase-list.module#PurchaseListPageModule', canActivate: [AuthGuardService] },
  { path: 'tabs', loadChildren: './tabs/tabs.module#TabsPageModule', canActivate: [AuthGuardService] },
  { path: 'service-list', loadChildren: './service-list/service-list.module#ServiceListPageModule', canActivate: [AuthGuardService] },
  { path: 'service/input', loadChildren: './service/input/input.module#ServiceInputPageModule', canActivate: [AuthGuardService] },
  { path: 'service/travel', loadChildren: './service/travel/travel.module#ServiceTravelPageModule', canActivate: [AuthGuardService] },
  { path: 'service/work', loadChildren: './service/work/work.module#ServiceWorkPageModule', canActivate: [AuthGuardService] },
  { path: 'report-list', loadChildren: './report-list/report-list.module#ReportListPageModule', canActivate: [AuthGuardService] },
  { path: 'report', loadChildren: './report/report.module#ReportPageModule', canActivate: [AuthGuardService] },
  { path: 'accounts-report', loadChildren: './accounts-report/accounts-report.module#AccountsReportPageModule', canActivate: [AuthGuardService] },
  { path: 'balance-report', loadChildren: './balance-report/balance-report.module#BalanceReportPageModule', canActivate: [AuthGuardService] },
  { path: 'cash-flow', loadChildren: './cash-flow/cash-flow.module#CashFlowPageModule', canActivate: [AuthGuardService] },
  { path: 'purchase-report', loadChildren: './purchase-report/purchase-report.module#PurchaseReportPageModule', canActivate: [AuthGuardService] },
  { path: 'result-report', loadChildren: './result-report/result-report.module#ResultReportPageModule', canActivate: [AuthGuardService] },
  { path: 'sale-report', loadChildren: './sale-report/sale-report.module#SaleReportPageModule', canActivate: [AuthGuardService] },
  { path: 'view-report', loadChildren: './view-report/view-report.module#ViewReportPageModule', canActivate: [AuthGuardService] },
  { path: 'dashboard', loadChildren: './dashboard/dashboard.module#DashboardPageModule', canActivate: [AuthGuardService] },
  { path: 'dashboard-list', loadChildren: './dashboard-list/dashboard-list.module#DashboardListPageModule', canActivate: [AuthGuardService] },
  { path: 'dashboard-filter', loadChildren: './dashboard-filter/dashboard-filter.module#DashboardFilterPageModule', canActivate: [AuthGuardService] },
  { path: 'person-tabs', loadChildren: './person-tabs/person-tabs.module#PersonTabsPageModule', canActivate: [AuthGuardService] },
  { path: 'report-tabs', loadChildren: './report-tabs/report-tabs.module#ReportTabsPageModule', canActivate: [AuthGuardService] },
  { path: 'importer', loadChildren: './importer/importer.module#ImporterPageModule', canActivate: [AuthGuardService] },
  { path: 'close', loadChildren: './cash/close/close.module#ClosePageModule', canActivate: [AuthGuardService] },
  { path: 'receivable-report', loadChildren: './receivable-report/receivable-report.module#ReceivableReportPageModule', canActivate: [AuthGuardService] },
  { path: 'payable-report', loadChildren: './payable-report/payable-report.module#PayableReportPageModule', canActivate: [AuthGuardService] },
  { path: 'production', loadChildren: './production/production.module#ProductionPageModule', canActivate: [AuthGuardService] },
  { path: 'production-list', loadChildren: './production-list/production-list.module#ProductionListPageModule', canActivate: [AuthGuardService] },
  { path: 'production-report', loadChildren: './production-report/production-report.module#ProductionReportPageModule', canActivate: [AuthGuardService] },
  { path: 'service-report', loadChildren: './service-report/service-report.module#ServiceReportPageModule', canActivate: [AuthGuardService] },
  { path: 'brand-list', loadChildren: './brand-list/brand-list.module#BrandListPageModule', canActivate: [AuthGuardService] },
  { path: 'brand', loadChildren: './brand/brand.module#BrandPageModule', canActivate: [AuthGuardService] },
  { path: 'stock-report', loadChildren: './stock-report/stock-report.module#StockReportPageModule', canActivate: [AuthGuardService] },
  { path: 'agro-tabs',loadChildren: './agro-tabs/agro-tabs.module#AgroTabsPageModule', canActivate: [AuthGuardService] },
  { path: 'animal', loadChildren: './animal/animal.module#AnimalPageModule', canActivate: [AuthGuardService] },
  { path: 'area', loadChildren: './area/area.module#AreaPageModule', canActivate: [AuthGuardService] },
  { path: 'areas', loadChildren: './areas/areas.module#AreasPageModule', canActivate: [AuthGuardService] },
  { path: 'animals', loadChildren: './animals/animals.module#AnimalsPageModule', canActivate: [AuthGuardService] },
  { path: 'machine', loadChildren: './machine/machine.module#MachinePageModule', canActivate: [AuthGuardService] },
  { path: 'machines', loadChildren: './machines/machines.module#MachinesPageModule', canActivate: [AuthGuardService] },
  { path: 'crop', loadChildren: './crop/crop.module#CropPageModule', canActivate: [AuthGuardService] },
  { path: 'crops', loadChildren: './crops/crops.module#CropsPageModule', canActivate: [AuthGuardService] },
  { path: 'work', loadChildren: './work/work.module#WorkPageModule', canActivate: [AuthGuardService] },
  { path: 'works', loadChildren: './works/works.module#WorksPageModule', canActivate: [AuthGuardService] },
  { path: 'activity', loadChildren: './activity/activity.module#ActivityPageModule', canActivate: [AuthGuardService] },
  { path: 'activitys', loadChildren: './activitys/activitys.module#ActivitysPageModule', canActivate: [AuthGuardService] },
  { path: 'activity-report', loadChildren: './activity-report/activity-report.module#ActivityReportPageModule', canActivate: [AuthGuardService] },
  { path: 'field', loadChildren: './field/field.module#FieldPageModule', canActivate: [AuthGuardService] },
  { path: 'input', loadChildren: './input/input.module#InputPageModule', canActivate: [AuthGuardService] },
  { path: 'inputs', loadChildren: './inputs/inputs.module#InputsPageModule', canActivate: [AuthGuardService] },
  { path: 'filter', loadChildren: './filter/filter.module#FilterPageModule', canActivate: [AuthGuardService] },
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
